export const LOGIN_PENDING = 'LOGIN_PENDING'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILED = 'LOGIN_FAILED'

export const VERIFY_ADMIN_PENDING = 'VERIFY_ADMIN_PENDING'
export const VERIFY_ADMIN_SUCCESS = 'VERIFY_ADMIN_SUCCESS'
export const VERIFY_ADMIN_FAILED = 'VERIFY_ADMIN_FAILED'

export const LOGOUT_USER = 'LOGOUT_USER'
