export const USER_LIST_PENDING = 'USER_LIST_PENDING'
export const USER_LIST_SUCCESS = 'USER_LIST_SUCCESS'
export const USER_LIST_FAILED = 'USER_LIST_FAILED'
export const USER_LIST_UPDATING = 'USER_LIST_UPDATING'
export const USER_LIST_UPDATED = 'USER_LIST_UPDATED'

export const USER_ADD_PENDING = 'USER_ADD_PENDING'
export const USER_ADD_SUCCESS = 'USER_ADD_SUCCESS'
export const USER_ADD_FAILED = 'USER_ADD_FAILED'

export const USER_UPDATE_PENDING = 'USER_UPDATE_PENDING'
export const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS'
export const USER_UPDATE_FAILED = 'USER_UPDATE_FAILED'

export const USER_DELETE_PENDING = 'USER_DELETE_PENDING'
export const USER_DELETE_SUCCESS = 'USER_DELETE_SUCCESS'
export const USER_DELETE_FAILED = 'USER_DELETE_FAILED'

export const SET_USER_ACTIVE_STATUS_PENDING = 'SET_USER_ACTIVE_STATUS_PENDING'
export const SET_USER_ACTIVE_STATUS_SUCCESS = 'SET_USER_ACTIVE_STATUS_SUCCESS'
export const SET_USER_ACTIVE_STATUS_FAILED = 'SET_USER_ACTIVE_STATUS_FAILED'

export const FETCH_SINGLE_USER_PENDING = 'FETCH_SINGLE_USER_PENDING'
export const FETCH_SINGLE_USER_SUCCESS = 'FETCH_SINGLE_USER_SUCCESS'
export const FETCH_SINGLE_USER_FAILED = 'FETCH_SINGLE_USER_FAILED'

export const FETCH_USER_WITHOUT_LICENSE_PENDING = 'FETCH_USER_WITHOUT_LICENSE_PENDING'
export const FETCH_USER_WITHOUT_LICENSE_SUCCESS = 'FETCH_USER_WITHOUT_LICENSE_SUCCESS'
export const FETCH_USER_WITHOUT_LICENSE_FAILED = 'FETCH_USER_WITHOUT_LICENSE_FAILED'
