export const FETCH_BRANDED_SMS_PENDING = 'FETCH_BRANDED_SMS_PENDING'
export const FETCH_BRANDED_SMS_SUCCESS = 'FETCH_BRANDED_SMS_SUCCESS'
export const FETCH_BRANDED_SMS_FAILED = 'FETCH_BRANDED_SMS_FAILED'

export const BRANDED_SMS_CHANGE_STATUS_PENDING = 'BRANDED_SMS_CHANGE_STATUS_PENDING'
export const BRANDED_SMS_CHANGE_STATUS_SUCCESS = 'BRANDED_SMS_CHANGE_STATUS_SUCCESS'
export const BRANDED_SMS_CHANGE_STATUS_FAILED = 'BRANDED_SMS_CHANGE_STATUS_FAILED'

export const FETCH_BRANDED_SMS_BY_ID_PENDING = 'FETCH_BRANDED_SMS_BY_ID_PENDING'
export const FETCH_BRANDED_SMS_BY_ID_SUCCESS = 'FETCH_BRANDED_SMS_BY_ID_SUCCESS'
export const FETCH_BRANDED_SMS_BY_ID_FAILED = 'FETCH_BRANDED_SMS_BY_ID_FAILED'
export const SET_BRANDED_SMS_CREDIT_BY_ID = 'SET_BRANDED_SMS_CREDIT_BY_ID'

export const ADD_CREDIT_BRANDED_SMS_PENDING = 'ADD_CREDIT_BRANDED_SMS_PENDING'
export const ADD_CREDIT_BRANDED_SMS_SUCCESS = 'ADD_CREDIT_BRANDED_SMS_SUCCESS'
export const ADD_CREDIT_BRANDED_SMS_FAILED = 'ADD_CREDIT_BRANDED_SMS_FAILED'

export const EDIT_CREDIT_BRANDED_SMS_PENDING = 'EDIT_CREDIT_BRANDED_SMS_PENDING'
export const EDIT_CREDIT_BRANDED_SMS_SUCCESS = 'EDIT_CREDIT_BRANDED_SMS_SUCCESS'
export const EDIT_CREDIT_BRANDED_SMS_FAILED = 'EDIT_CREDIT_BRANDED_SMS_FAILED'

export const DELETE_CREDIT_BRANDED_SMS_PENDING = 'DELETE_CREDIT_BRANDED_SMS_PENDING'
export const DELETE_CREDIT_BRANDED_SMS_SUCCESS = 'DELETE_CREDIT_BRANDED_SMS_SUCCESS'
export const DELETE_CREDIT_BRANDED_SMS_FAILED = 'DELETE_CREDIT_BRANDED_SMS_FAILED'
