export const FETCH_BRANDED_SMS_PENDING = 'FETCH_BRANDED_SMS_PENDING'
export const FETCH_BRANDED_SMS_SUCCESS = 'FETCH_BRANDED_SMS_SUCCESS'
export const FETCH_BRANDED_SMS_FAILED = 'FETCH_BRANDED_SMS_FAILED'

export const BRANDED_SMS_CHANGE_STATUS_PENDING = 'BRANDED_SMS_CHANGE_STATUS_PENDING'
export const BRANDED_SMS_CHANGE_STATUS_SUCCESS = 'BRANDED_SMS_CHANGE_STATUS_SUCCESS'
export const BRANDED_SMS_CHANGE_STATUS_FAILED = 'BRANDED_SMS_CHANGE_STATUS_FAILED'
