export const LICENSE_LISTS_FETCHING = 'LICENSE_LISTS_FETCHING'
export const LICENSE_LISTS_FETCHED = 'LICENSE_LISTS_FETCHED'
export const LICENSE_LISTS_FAILED = 'LICENSE_LISTS_FAILED'

export const LICENSE_ADD_PENDING = 'LICENSE_ADD_PENDING'
export const LICENSE_ADD_SUCCESS = 'LICENSE_ADD_SUCCESS'
export const LICENSE_ADD_FAILED = 'LICENSE_ADD_FAILED'

export const LICENSE_EDIT_PENDING = 'LICENSE_EDIT_PENDING'
export const LICENSE_EDIT_SUCCESS = 'LICENSE_EDIT_SUCCESS'
export const LICENSE_EDIT_FAILED = 'LICENSE_EDIT_FAILED'

export const LICENSE_DELETE_PENDING = 'LICENSE_DELETE_PENDING'
export const LICENSE_DELETE_SUCCESS = 'LICENSE_DELETE_SUCCESS'
export const LICENSE_DELETE_FAILED = 'LICENSE_DELETE_FAILED'

export const LICENSE_FINDONE_PENDING = 'LICENSE_FINDONE_PENDING'
export const LICENSE_FINDONE_SUCCESS = 'LICENSE_FINDONE_SUCCESS'
export const LICENSE_FINDONE_FAILED = 'LICENSE_FINDONE_FAILED'

export const LICENSE_MEMBERS_LISTS_PENDING = 'LICENSE_MEMBERS_LISTS_PENDING'
export const LICENSE_MEMBERS_LISTS_SUCCESS = 'LICENSE_MEMBERS_LISTS_SUCCESS'
export const LICENSE_MEMBERS_LISTS_FAILED = 'LICENSE_MEMBERS_LISTS_FAILED'

export const LICENSE_MEMBERS_SAVE_PENDING = 'LICENSE_MEMBERS_SAVE_PENDING'
export const LICENSE_MEMBERS_SAVE_SUCCESS = 'LICENSE_MEMBERS_SAVE_SUCCESS'
export const LICENSE_MEMBERS_SAVE_FAILED = 'LICENSE_MEMBERS_SAVE_FAILED'
